"""
run_archiver.py — Archives simulation result images and metrics after each run.

All plot images are copied into a single `dashboard_runs/` folder with the
run's datetime stamp appended to each filename.  A JSON metadata file is also
written per run so the dashboard can reconstruct history.

Usage (called automatically at the end of main.main):
    import run_archiver
    run_archiver.archive_run(results_dict, seed)
"""
import os
import json
import glob
import shutil
from datetime import datetime

import config
import metrics as sim_metrics

# ── Where all archived images and metadata live ──────────────────────────────
ARCHIVE_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "dashboard_runs")

# Images generated by visualize.py and train.py that we archive
_PLOT_GLOBS = [
    "plot_*.png",
    "mesh_animation.gif",
    "confusion_matrix.png",
    "loss_curves.png",
    "plot_confusion_matrix.png",
]


def _ensure_dir():
    os.makedirs(ARCHIVE_DIR, exist_ok=True)


def _timestamp_str():
    """Return a filesystem-safe timestamp like 20260826_110530."""
    return datetime.now().strftime("%Y%m%d_%H%M%S")


def archive_run(results: dict, seed: int):
    """
    Copy every generated plot into dashboard_runs/ with timestamp suffix,
    and write a run_<timestamp>.json metadata file.

    Parameters
    ----------
    results : dict   — the dictionary returned by main.main()
    seed    : int    — the random seed used for this run
    """
    _ensure_dir()
    ts = _timestamp_str()
    project_root = os.path.dirname(os.path.abspath(__file__))

    # ── 1. Copy images ───────────────────────────────────────────────────────
    copied_images = []
    latest_dir = os.path.join(project_root, "latest_runs")
    search_dirs = [latest_dir, project_root]

    seen = set()
    for pattern in _PLOT_GLOBS:
        for sdir in search_dirs:
            if not os.path.exists(sdir):
                continue
            for src_path in glob.glob(os.path.join(sdir, pattern)):
                basename = os.path.basename(src_path)
                if basename in seen:
                    continue
                seen.add(basename)
                name, ext = os.path.splitext(basename)
                dest_name = f"{name}_{ts}{ext}"
                dest_path = os.path.join(ARCHIVE_DIR, dest_name)
                shutil.copy2(src_path, dest_path)
                copied_images.append(dest_name)

    # ── 2. Compute metrics ───────────────────────────────────────────────────
    tasks = results.get("tasks", [])
    completion_timestamps = results.get("completion_timestamps", {})
    availability_log = results.get("availability_log", {})
    fault_log = results.get("fault_log", {})
    deadlock_log = results.get("deadlock_log", [])
    total_sent = results.get("total_sent", 0)
    total_dropped = results.get("total_dropped", 0)
    energy_log = results.get("energy_log", {})
    tasks_completed_count = results.get("tasks_completed_count", 0)
    auction_iterations_log = results.get("auction_iterations_log", [])
    connectivity_log = results.get("connectivity_log", [])
    physics_log = results.get("physics_log", {})
    thermocline_messages = results.get("thermocline_messages", 0)
    congestion_drops = results.get("congestion_drops", 0)

    metrics_data = {
        "task_completion_rate": sim_metrics.task_completion_rate(tasks),
        "mean_task_completion_time": sim_metrics.mean_task_completion_time(completion_timestamps),
        "system_throughput": sim_metrics.system_throughput(tasks, config.SIMULATION_TIMESTEPS),
        "mean_amv_availability": sim_metrics.mean_amv_availability(availability_log),
        "fault_impact_score": sim_metrics.fault_impact_score(fault_log),
        "deadlock_frequency": sim_metrics.deadlock_frequency(deadlock_log, config.SIMULATION_TIMESTEPS),
        "mean_packet_loss_rate": sim_metrics.mean_packet_loss_rate(total_sent, total_dropped),
        "energy_efficiency": sim_metrics.energy_efficiency(energy_log, tasks_completed_count),
        "auction_convergence_rate": sim_metrics.auction_convergence_rate(auction_iterations_log),
        "connectivity_maintenance": sim_metrics.connectivity_maintenance_rate(connectivity_log),
        "physics_impact_on_faults": sim_metrics.physics_impact_on_faults(physics_log, fault_log),
        "thermocline_crossing_penalty": sim_metrics.thermocline_crossing_penalty(thermocline_messages, total_sent),
        "congestion_drop_rate": congestion_drops / max(total_sent, 1),
        "congestion_drops": congestion_drops,
        "mean_task_delay": results.get("mean_task_delay", 0.0),
        "max_task_delay": results.get("max_task_delay", 0.0),
        "never_completed_tasks": results.get("never_completed_tasks", 0),
        "stalled_amv_timesteps": results.get("stalled_amv_timesteps", 0),
        "total_deadlocks": len(deadlock_log),
    }

    # ── 3. AMV final states ──────────────────────────────────────────────────
    amvs = results.get("amvs", [])
    amv_states = []
    for amv in amvs:
        amv_states.append({
            "amv_id": amv.amv_id,
            "energy": round(amv.energy, 2),
            "fault_state": amv.fault_state,
            "fsm_state": amv.fsm_state,
            "tasks_completed": len(amv.tasks_completed),
            "distance_traveled": round(amv.distance_traveled, 1),
        })

    # ── 4. Write run metadata JSON ───────────────────────────────────────────
    run_meta = {
        "timestamp": ts,
        "datetime_iso": datetime.now().isoformat(),
        "seed": seed,
        "scenario": config.STRESS_SCENARIO,
        "allocator": config.ALLOCATOR_MODE,
        "n_amvs": config.N_AMVS,
        "n_tasks": config.N_TASKS,
        "simulation_timesteps": config.SIMULATION_TIMESTEPS,
        "metrics": metrics_data,
        "amv_states": amv_states,
        "images": copied_images,
    }

    meta_path = os.path.join(ARCHIVE_DIR, f"run_{ts}.json")
    with open(meta_path, "w") as f:
        json.dump(run_meta, f, indent=2)

    # ── 5. Update master runs index ──────────────────────────────────────────
    index_path = os.path.join(ARCHIVE_DIR, "runs_index.json")
    if os.path.exists(index_path):
        with open(index_path, "r") as f:
            index = json.load(f)
    else:
        index = {"runs": []}

    index["runs"].append({
        "timestamp": ts,
        "datetime_iso": datetime.now().isoformat(),
        "seed": seed,
        "scenario": config.STRESS_SCENARIO,
        "allocator": config.ALLOCATOR_MODE,
        "meta_file": f"run_{ts}.json",
        "task_completion_rate": metrics_data["task_completion_rate"],
        "total_deadlocks": metrics_data["total_deadlocks"],
        "mean_task_delay": metrics_data["mean_task_delay"],
    })

    with open(index_path, "w") as f:
        json.dump(index, f, indent=2)

    print(f"\n{'='*60}")
    print(f"RUN ARCHIVED → dashboard_runs/")
    print(f"  Timestamp:  {ts}")
    print(f"  Images:     {len(copied_images)} files copied")
    print(f"  Metadata:   run_{ts}.json")
    print(f"{'='*60}")
